# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Twelve Strings
# email: john [at] johncyril [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Musings, food reviews, recipes, rants, photos, code snippets - maybe even some recorded music!
  Who knows? All I promise is that *I* find it interesting.. or amusing.. or writing it is nursing my tortureds soul.. Your mileage may likely vary.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johncyril.com" # the base hostname & protocol for your site
twitter_username: johncyril
github_username:  johncyril
instagram_username: john.cyril
soundcloud_username: 


# Build settings
markdown: kramdown
